### ISSUE TITLE
cell text not displayed

### ISSUE THREAD

**Issue by ADEL-EL-GAZAR** [ekondur/ef-datatable.js#106]
**Describe the bug**
data retrieved from DB successfully but it displays rows without its content

**Screenshots**
![Screenshot 2022-12-11 144609](https://user-images.githubusercontent.com/12661307/206904388-e60d9ac4-6e82-4ff0-9954-810db8e164d8.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by ekondur** [comment]
Hi @ADEL-EL-GAZAR ,
You probably have an issue same as here: https://github.com/ekondur/DatatableJS/issues/90
Can you pls check the serialization settings?

**Comment by ekondur** [comment]
Hi @ADEL-EL-GAZAR ,
You can use it from now on,
```csharp
.URL(Url.Action("GetDataResult"), "POST", camelCase: true)
```
Set the camelCase property to `true`.
It is released with version [3.4.1](https://github.com/ekondur/DatatableJS/releases/tag/v3.4.1)
