### ISSUE TITLE
keyword in filtering column not showing when state save is true and user reload page

### ISSUE THREAD

**Issue by nazerulgit** [ekondur/ef-datatable.js#118]
**Describe the bug**
when state save is true and user search by any column in individual search and then user refresh it, the content of table showing with filtered data but the keyword not showing up in input type of column,
so if we want to showing up all data we must memorize which search column is typed and then press [backspace[]

**Comment by ekondur** [comment]
Hi @nazerulgit 
It is fixed with v.3.6.1 https://github.com/ekondur/DatatableJS/releases/tag/v3.6.1
Please update your package. 
Thanks for your contribution

**Comment by nazerulgit** [comment]
yes sir, allready fixed in 3.6.1 version
thanks sir
