### ISSUE TITLE
command onclick event in commands only uses numeric values but not strings.

### ISSUE THREAD

**Issue by serkansmg** [ekondur/ef-datatable.js#123]
**Describe the bug**
here is the table. 
Id column is Guid

`
var userTable = Html.JS().Datatable<redisUserModel>()
.Name("redisUsers")
.Columns(col =>
{
col.Field(a => a.ServerName).Title("Server").Searchable(true);
col.Field(a => a.UserName).Title("UserName").Searchable(true);
col.Field(a => a.Id).Title("Id").Visible(false);
col.Field(a => a.redisUser).Title("redisUser").Searchable(true)
Template("(row.redisUser==null)?`<span class=\"badge bg-danger\">Not Set</span>`:`${data}`");
col.Field(a => a.online).Title("online").Visible(true)
.Template("(row.online!=true)?`<span class=\"badge bg-danger\">OFFLINE</span>`:`<span class=\"badge bg-green\">Online</span>`"); 
col.Field(a => a.Id).Title("Id").Searchable(true)
.Template("getButtons(row.redisUser,row.id)");
col.Commands(a => a.Id, new[] {
		new Command("<button class=\"btn btn-primary\"><span class=\"fas fa-user-check\"></span>&nbsp;Reset Perm</button>","resetRedisUser"),
		new Command("<button class=\"btn btn-danger\"><span class=\"fas fa-user-minus\"></span>&nbsp;Del RUser</button>","deleteRedisUser"),
		new Command("<button class=\"btn btn-warning\"><span class=\"fas fa-user-lock\"></span>&nbsp;Change Pwd</button>","changePassword"),
		new Command("<button class=\"btn btn-green\"><span class=\"fas fa-server\"></span>&nbsp;Online Stats</button>","getOnlineStatus"),
		new Command("<button class=\"btn btn-yellow\"><span class=\"fas fa-desktop\"></span>&nbsp;Device  List</button>","getdeviceStatus"),
		new Command("<button class=\"btn btn-secondary\"><span class=\"fas fa-server\"></span>&nbsp;Raw Sql</button>","getRawSql"),
		new Command("<button class=\"btn btn-blue\"><span class=\"fas fa-bullseye\"></span>&nbsp;Ping Server</button>","getPing")
}, "Actions");

})
.Data("function(){var obj={serverName:selectedServer}; console.log('data:',JSON.stringify( obj));  return  obj;}")
.Language("/js/Turkish.json")
.URL(Url.Action("getRedisServerUsers", "redisAdmin"), "POST", camelCase: true)
.Processing(false).Searching(false).ColReorder(false)
.ServerSide(true).Class("table table-striped table-bordered align-middle table-responsive dt-responsive")
;

`

each button only accepts function name but;
-  does not allow any column manipulation 
- only thinks onclick event sends a numeric value
- not detects type of column, if it can, it may show guid as 'guid-value'

**Comment by serkansmg** [comment]
and also, how can i add printi, export, excel,csv, pdf buttons ?
any example?

**Comment by ekondur** [comment]
Hello @serkansmg 
It was fixed and released with the 3.8.1 version. Thank you for your contribution. 

By the way, print buttons are only for example to show buttons.
