### ISSUE TITLE
Error When Set Selecting(true, SelectItems.Checkbox)

### ISSUE THREAD

**Issue by nazerulgit** [ekondur/ef-datatable.js#140]
this error is showing up when i set selecting to Selecting(true, SelectItems.Checkbox)

System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   
   this is my complete view code
   
   
    @(Html.JS().Datatable<Person>()
    .Class("table table-hovered table-striped dataTable")
    .Name("datatable")
    .LengthMenu(new int[] { 5, 10, 25, 50, 100 }, true, "All Pages")
    .FixedColumns(leftColumns: 0, rightColumns: 1)

    .ColumnSearching(true, "form-control", SearchPosition.Header)
    .Columns(cols =>
    {
    cols.Field(a => a.PerId).Title("Id");
    cols.Field(a => a.PerName).Title("Name");
    cols.Field(a => a.PerAddr1).Title("House No");
    cols.Field(a => a.PerAddr2).Title("Street Name");
    cols.Field(a => a.PerAddr3).Title("Unit");
    cols.Field(a => a.PerTelMobile).Title("Mobile");
    cols.Field(a => a.category).Title("Category");
    cols.Field(a => a.PerEmail).Title("Email");
    })
    .ColReorder(true)
    .Orders(order =>
    {
    order.Add(p => p.PerId, OrderBy.Descending);
    })
    .URL(Url.Action("GetDataResultPeople"), "POST")
    .ServerSide(true)
    .StateSave(true)
    .Selecting(true, SelectItems.Checkbox)
    .Render()
    )
    
    when i check the html created i realized that variable name in column defined datatable is ''
    
        <html>
<body>

columns: [{
--
  | data: '',
  | name: '',
  | defaultContent: '',
  | orderable: false,
  | searchable: false,
  | className: 'select-checkbox',
  | visible: true,
  | width: '5%',
  |  
  | }, {

</body>
</html>

thank you

Nasrul
Regards

**Comment by ekondur** [comment]
Hi  @nazerulgit 
Is your package up to date?

**Comment by nazerulgit** [comment]
Hi @ekondur 
yes my package is up to date
i use version 3.9.0 for DatatableJS
and use version 3.8.0 for DatatableJS.Data

**Comment by ekondur** [comment]
Hi @nazerulgit 
It was fixed and released with v3.9.1

**Comment by nazerulgit** [comment]
hi @ekondur 
yes thank you so much
its working now
