### ISSUE TITLE
Individual Column Searching

### ISSUE THREAD

**Issue by tekoscott** [ekondur/ef-datatable.js#33]
I am currently using EFDatatable and I think it is an excellent project. I would like to inquire if you support individaul column searching https://datatables.net/examples/api/multi_filter.html

**Comment by vpalhories** [comment]
Assuming you’re using version 1.10 of the Datatables, you would need to install the Search API.  
Have a look here:  https://datatables.net/reference/api/column().search()

**Comment by ekondur** [comment]
Hi @tekoscott It is not support yet but it is really good idea. I think we will develop it as soon as possible. Thanks

**Comment by tekoscott** [comment]
Hi @ekondur thanks for that. And once again thanks for an excellent project. This is now my goto tool for creating datatables with MVC. Keep up the good work.

**Comment by ekondur** [comment]
Hi @tekoscott I released this issue with release [1.3.0](https://github.com/ekondur/EFDatatable/releases/tag/v1.3.0) 
Please update nuget package and use it :)
Thanks for contribution.
