### ISSUE TITLE
Column Searching Input fields in footer with fixed width

### ISSUE THREAD

**Issue by tekoscott** [ekondur/ef-datatable.js#38]
Thank you for implementing columns searching. This is a very useful feature and I am currently implementing it into my projects.

One issue that i have noticed is that when column searching is enabled the input controls used for searching are a fixed width. This means that when many columns are used the width of the column cannot resized any smaller that the input control

Kind Regards

Scott

**Comment by ekondur** [comment]
Hi @tekoscott , thanks for feedback, I released it with v1.3.1
See you next issues.

**Comment by tekoscott** [comment]
Awesome! Thanks for that.. Works great.

In the sample app you have a style that limits input fields  to a maximum width of 280px.

So once i notice that, for my project, all i had to do was change the style element from

/* Set width on the form input elements since they're 100% wide by default */
input,
select,
textarea {
    max-width: 280px;
}

to

/* Set width on the form input elements since they're 100% wide by default */
input,
select,
textarea {
    max-width: 100%;
}

**Comment by ekondur** [comment]
It is not necessary anymore. I added to style of these column search inputs: width 100%, you can change column size so inputs are compatible with
