### ISSUE TITLE
Individual Column Searching with Dates

### ISSUE THREAD

**Issue by tekoscott** [ekondur/ef-datatable.js#41]
Not sure its possible.

I have noticed that trying to filter a date based column does not work, specifically when getdataresult returns a jsonresult

Kind Regards

Scott

**Comment by ekondur** [comment]
Hi @tekoscott
Do you use it server side or client side?

**Comment by tekoscott** [comment]
Server Side.

Tested with your sample EFDatatable.Web app as well and it exhibits the same behaviour. You can't filter by date.

**Comment by tekoscott** [comment]
In EFDatatable.Web, if you try to filter by "01-Jan-1980" it will just show "No matching records found" even though there is"

**Comment by ekondur** [comment]
Hi @tekoscott 
That was a server side data retrieve problem. I added a datepicker instead of text input when using grid as server side, so fixed it on version 1.3.2
thank you.
