### ISSUE TITLE
Column Searching By Date Does Not Account for time

### ISSUE THREAD

**Issue by tekoscott** [ekondur/ef-datatable.js#44]
Hi ekondur,

Column Searching does not work when the date has a time portion other than "12:00:00 AM"

To replicate the issue with your sample web application.

In the database add a BirthDate for Arya Stark of "19-Sep-1980 01:19 AM".

Compile and run the web application and try and search for for 19/09/1980

The record is not found because the time portion of the date does not match. 

It only works when the timestamps exactly match "12:00:00"

Kind Regards 

tekoscott

**Comment by ekondur** [comment]
Hi @tekoscott, i got it.
I will fix it soon.
Thank you.

**Comment by ekondur** [comment]
Hi @tekoscott 
I fixed it in [v1.3.3](https://github.com/ekondur/EFDatatable/releases/tag/v1.3.3) version, please test it.
Regards.

**Comment by tekoscott** [comment]
Thanks for that. Will test and let you know

**Comment by tekoscott** [comment]
Awesome thanks for that did testing and it works brilliantly. You can close this issue. Once again thanks.

**Comment by ekondur** [comment]
Thank you @tekoscott
