### ISSUE TITLE
.net Core 5 / 6

### ISSUE THREAD

**Issue by davidbuckleyni** [ekondur/ef-datatable.js#53]
Will this be upgraded ot support .net core 5 or 6 or at least include the nuget spec file so other people can do it it looks a good control.

**Comment by ekondur** [comment]
Hello @davidbuckleyni , it will support soon :)

**Comment by ekondur** [comment]
Hello @davidbuckleyni you can use these packages with new names DatatableJs...
Please use for any version of dotnetcore (.net5, .net6 etc.) this DatatableJS package
https://www.nuget.org/packages/DatatableJS/
