### ISSUE TITLE
.NET Core tag helps casing clashes with Jquery Datatables

### ISSUE THREAD

**Issue by ItzFender** [ekondur/ef-datatable.js#54]
```
<datatable name="PersonGrid">
    <columns>
        <column field="Id" class-name="id" visible="false" />
        <column field="LastName" width="50" title="Last Name" />
        <column field="FirstName" width="50" title="First Name" />
    </columns>
    <data-source url="@Url.Action("GetData")" method="POST" server-side="true" />
    <filters>
    </filters>
    <captions top="top caption here" bottom="bottom caption here" />
    <render />
</datatable>
```

Using the above code generates the jquery datatabels columns as is.

```
columns: [{ 
                                'data': 'Id',
                                'name': 'Id',
                                'defaultContent': '',
                                'orderable': true,
                                'searchable': true,
                                'className': 'id',
                                'visible': false,
                                'width': '0%',
                                    
                            }, { 
                                'data': 'LastName',
                                'name': 'LastName',
                                'defaultContent': '',
                                'orderable': true,
                                'searchable': true,
                                'className': '',
                                'visible': true,
                                'width': '50%',                                    
                            }, { 
                                'data': 'FirstName',
                                'name': 'FirstName',
                                'defaultContent': '',
                                'orderable': true,
                                'searchable': true,
                                'className': '',
                                'visible': true,
                                'width': '50%',                                    
                            }]
```

But when returning the `Json(context.People.ToDataResult(request));` the columned data is pascal cased.

The response of just the first record
`{"draw":2,"recordsTotal":245517,"recordsFiltered":245517,"data":[{"id":11,"lastName":"MyLastName","firstName":"MyFirstName"}]}`

Because of this it is not able to map the data to the columns and all the columns are empty.

I'm using:
-  DatatableJS and DatatableJS.Data 3.0.1
-  jquery.Datatables 1.10.19

![emptytable](https://user-images.githubusercontent.com/6775329/139716935-5c886448-464e-414e-af18-750dbd1dd909.PNG)

**Comment by ekondur** [comment]
Hello @ItzFender i will contact you soon to fix it

**Comment by ekondur** [comment]
Hi @ItzFender, I checked the example you wrote. If Person class you have that includes properties pascale cased then probably there is a json serializer issue. Please check project serialization settings.
[Maybe it helps you](https://stackoverflow.com/questions/38728200/how-to-turn-off-or-handle-camelcasing-in-json-response-asp-net-core)

**Comment by ItzFender** [comment]
I would add that the default JsonSerializerOptions.PropertyNamingPolicy is JsonNamingPolicy.CamelCase in .NET 5 and .net Core 3. I didn't bother looking further back then that. If this is how you intend it to work I would suggest making a note in the wiki and/or the readme documentation as it won't work without intentionally turning that off in the json serialization settings.

Personally I don't want to change the default json serailization because of potential downstream affects to other libraries that I'm using in my project. 

As a workaround I used camel casing for the column field names and changed it back to pascal casing in the controller.

```
<datatable name="PersonGrid">
    <columns>
        <column field="id" class-name="id" visible="false" />
        <column field="lastName" width="50" title="Last Name" />
        <column field="firstName" width="50" title="First Name" />
    </columns>
    <data-source url="@Url.Action("GetData")" method="POST" server-side="true" />
    <filters>
    </filters>
    <captions top="top caption here" bottom="bottom caption here" />
    <render />
</datatable>
```

```
public JsonResult GetData(DataRequest request)
        {
            foreach (var column in request.columns)
            {
                column.data = char.ToUpper(column.data[0]) + column.data[1..];
                column.name = char.ToUpper(column.name[0]) + column.name[1..];
            }

            foreach (var filter in request.filters)
            {
                filter.Field = char.ToUpper(filter.Field[0]) + filter.Field[1..];
            }
            
            var result = _productionContext.People
                .ToDataResult(request);
            return Json(result);
        }
```

**Comment by ekondur** [comment]
If you use property names pascal cased like FirstName and project serializer is default then json data shouldn't return camelcase @ItzFender

**Comment by ekondur** [comment]
Hi @ItzFender if the problem persists, we can debug together
