### ISSUE TITLE
Add column searching for tag helps

### ISSUE THREAD

**Issue by ItzFender** [ekondur/ef-datatable.js#55]
**Is your feature request related to a problem? Please describe.**
Column searching is missing in tag helpers

**Comment by ekondur** [comment]
Hi @ItzFender , i will review again, thanks your feedback

**Comment by ekondur** [comment]
Hi @ItzFender, it's not support column-searching in tag helper version yet. I will work on it and let you know.

**Comment by ekondur** [comment]
Hi @ItzFender, i add html helper support for .net core. All capabilites in there (v3.1.0), i can't add some of them in tag helper version. Thx for feedbacks.

PS: named datatable to js-datatable in tag helper to avoid conflicts
