### ISSUE TITLE
Add alternate display for commands 

### ISSUE THREAD

**Issue by rolujan** [ekondur/ef-datatable.js#63]
### Is your feature request related to a problem? Please describe.
My request does not have to do with a problem, it has to do with a **specific need**.

### Describe the solution you'd like

I **need** to **show multiple buttons** for each row **without** the **user having to make extra clicks**. 

In section **Additional context**, you will find a **screenshot** of the need and the solution described. 

### Describe alternatives you've considered

**I would add** a parameter with the **CommandType**, according to which you can specify whether you want to use the **dropdown-based display** or the **new button group-based display**. 

By **default**, if not specified, the **dropdwon-based display** will be used. 

**What version of bootstrap is the library using?**
In my project I use **bootstrap 5**, but from what I have seen I think the **library** is based on **bootstrap 4**. 

### Additional context
**Current display** of command feature (using **dropdown** from bootstrap):

![image](https://user-images.githubusercontent.com/32508403/147879436-58a7a932-046c-4b96-a264-5edfeb6dd89c.png)

Dropdown example code:
```
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
    Actions
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Excel</a>
    <a class="dropdown-item" href="#">Pdf</a>
  </div>
</div>
```

**Suggested alternate display** of command feature (using **button group** from bootstrap):

![image](https://user-images.githubusercontent.com/32508403/147879500-8054e0ac-22a4-4f55-86b0-54d871e93a09.png)

Button group example code:
```
<div class="btn-group">
  <a href="#" class="btn btn-primary">Show</a>
  <a href="#" class="btn btn-primary">Edit</a>
  <a href="#" class="btn btn-primary">Delete</a>
</div>
```

**If we can agree on how to do it, I can develop this feature and contribute to the project.**

Best regards

**Comment by ekondur** [comment]
Hi @rolujan, it is a good idea that alternate button group, thanks for support :)

**Comment by ekondur** [comment]
Hi @rolujan, are you currently working on this?

**Comment by rolujan** [comment]
> Hi @rolujan, are you currently working on this?

Hi @ekondur, yesterday i didn't have time to get on with it.

The idea, if I have time is to do it myself, unless you have started it or you prefer to do it yourself.

**Comment by ekondur** [comment]
Ok, when I start, I will notify you, thank you @rolujan

**Comment by ekondur** [comment]
Hi @rolujan , it supports also Command shows bellow, is it not useful?
![resim](https://user-images.githubusercontent.com/4971326/148209015-6fb9e025-e7ca-4724-afd3-2d28f3589ccf.png)
PS: we can still add alternate button group you offer :)
