### ISSUE TITLE
Commands not working with bootstrap 5

### ISSUE THREAD

**Issue by nazerulgit** [ekondur/ef-datatable.js#82]
**Describe the bug**
tag helper commands not working with bootstrap 5, because it still use attribute data-toggle instead of data-bs-toggle, so the dropdown is not showing up

**To Reproduce**
1. Go to 'CommandsHelper.cs' in folder Helpers
2. Scroll down to line 43
4. add condition to detect which version of bootstrap is used in theme

**Expected behavior**
datatableJs can used in every version of bootstrap

**Comment by ekondur** [comment]
Hi @nazerulgit
It has fixed with version [3.2.5](https://www.nuget.org/packages/DatatableJS/3.2.5)
Thank you!
