### ISSUE TITLE
Checkbox selection

### ISSUE THREAD

**Issue by nazerulgit** [ekondur/ef-datatable.js#84]
your library is very help full for us
i am very thank full to you
is your library can use for checkbox selection as this link
https://datatables.net/extensions/select/examples/initialisation/checkbox.html

so when user make one or more selection in this checkbox will showing up a button that if the user click that button will send to function with ids selected

**Comment by ekondur** [comment]
Hi @nazerulgit 
The Selecting behavior is added, to add checkbox functionality, just use it:
```csharp
.Selecting(true, SelectItems.Checkbox)
```
Thank you for the suggestion.

PS: It is released with the 3.3.0 version. If you use `.ToDataResult()` extension to retrieve data, you should update also DatatableJs.Data package.
