### ISSUE TITLE
English ("United States") is an invalid Culture identifier

### ISSUE THREAD

**Issue by madcoda9000** [ekondur/ef-datatable.js#92]
**Describe the bug**
you've a bug in DatableJs.Data Projectfile. 

If you use localization in your project beside DatatablesJs.Data you'll get the following error:

`Culture is not supported. Parameter name: name English ("United States") is an invalid culture identifier. Exception Details: System.Globalization.CultureNotFoundException: Culture is not supported. Parameter name: name English ("United States") is an invalid culture identifier.`

**To Reproduce**
1. create an .net core 6 mvc project
2. implement localization 
3. add DatatablesJs NuGet Package
4. create a controller using DatatablesJs.Data & a view where you use DatatableJs Grid.

**Desktop (please complete the following information):**
 - OS: MacOs Ventura
 - Browser Chrome

**Additional context**
This is reproduce able and makes totally sense as English ("United States") is not a supported culture value. A valid culture value would be de or en for ex.

I could get rid of that bug by doing the following:

1. clone DatattablesJs locally
2. modify DatatablesJs.Data.csproj

change
`<NeutralLanguage>English ("United States")</NeutralLanguage>   `

to:
`<NeutralLanguage>en</NeutralLanguage>   `

3. compile DatatablesJs
4. use the newly compiled Assemblys in your project.

**Comment by ekondur** [comment]
Hi @madcoda9000 
If you want to be a contributor,  you can send a pull request for this.

**Comment by madcoda9000** [comment]
Hi @ekondur ,

i did as you suggested. As this is my first pull request ever, i hope i did erverything correct :-)

**Comment by ekondur** [comment]
Hi @madcoda9000, 
Thanks for your participation,  we need to separate issues by item, for this change pls just send the culture issue.
We can handle other things with the other issues, 
Regards.

**Comment by madcoda9000** [comment]
Hi @ekondur 

ok, i've deleted the pull request an created a new one, only for this issue

**Comment by ekondur** [comment]
Welcome to team @madcoda9000 :)
I approved PR, for other items I will update you, thank you

**Comment by ekondur** [comment]
It is released with v3.3.2
