### ISSUE TITLE
Removing data null check in Template

### ISSUE THREAD

**Issue by ekondur** [ekondur/ef-datatable.js#95]
We should remove the **data** null check here,

` {(string.IsNullOrEmpty(a.Render) ? string.Empty : $"'render': function(data, type, row, meta) {{ if (data == null) {{ return ''; }} else {{ return {a.Render}; }} }}")}`
   **to :**
` {(string.IsNullOrEmpty(a.Render) ? string.Empty : $"'render': function(data, type, row, meta) {{ return {a.Render}; }}")}`

Users can add a null check manually when defining `.Template`

`.Template("(data === 'Y') ? 'Yes' : (data === null) ? 'None' : 'No'");`

These files might be affected:

- DatatableJS -> JSHelper.cs
- DatatableJS -> RenderHelper.cs
- DatatableJS.Net -> JSHelper.cs

**Comment by ekondur** [comment]
Hi @madcoda9000 ;
You have found this issue, do you want to make it?

**Comment by madcoda9000** [comment]
Sure, I'll do a pull request for that issue.

**Comment by madcoda9000** [comment]
Hi @ekondur 

I've created the pull request

**Comment by madcoda9000** [comment]
sorry, i've to made a new pull request. I am quite confused. When i create a new pull request, github takes ALL commits into that pull request. How can i specify which commit should be taken for the pull request?

Sorry to bother you with such questions :-)

**Comment by ekondur** [comment]
Hi @madcoda9000,
Everything seems fine for you PR :) There is just one commit in there.
Thank you for your contribution.

**Comment by ekondur** [comment]
It is released with v3.3.2
